spring:
  application:
    name: PersonalLibraryService

library:
  name: Production Library
  mode: production

logging:
  level:
    com.sprints.PersonalLibraryService: INFO
    org.springframework.boot: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
