spring:
  application:
    name: PersonalLibraryService

library:
  name: Development Library
  mode: development

app:
  email: dev-library@example.com
  phone: +1-555-0124

logging:
  level:
    com.sprints.PersonalLibraryService: DEBUG
    org.springframework.boot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8080
